language: ruby
rvm:
  - 2.2
  - 2.3.0
# https://lord.io/blog/2014/travis-multiple-subdirs/
env:
  - TEST_DIR=examples/new-words/api
script: cd $TEST_DIR && bundle install --without development && rake
before_install:
  - sudo apt-get install -y rabbitmq-server
services:
  - rabbitmq
sudo: required
