source 'https://rubygems.org'

gem 'sinatra', '~>1'
gem 'rake'
gem 'rack-request-id'

group :development do
  gem 'overcommit', '=0.25.0'
  gem 'guard-rspec'
  gem 'guard-rubocop', '~>1.2'
  gem 'byebug'
end

group :test do
  gem 'rubocop', '~>0.30', require: false
  gem 'rspec', '~>3'
  gem 'rack-test'
  gem 'simplecov', require: false
  gem 'coveralls', require: false
end
