source 'https://rubygems.org'

gem 'sinatra', '~>1'

group :development, :test do
  gem 'guard-rspec'
  gem 'guard-rubocop', '~>1.2'
  gem 'rubocop', '~>0.30', require: false
  gem 'rspec', '~>3'
  gem 'rack-test'
  gem 'overcommit', '=0.25.0'
  gem 'rake'
  gem 'simplecov', require: false
  gem 'coveralls', require: false
end
