source 'https://rubygems.org'

gem 'sinatra', '~>1'

group :development, :test do
  gem 'guard-rspec'
  gem 'rubocop', '~>0.30', require: false
  gem 'rspec', '~>3'
  gem 'debugger'
  gem 'rack-test'
  gem 'overcommit', '=0.25.0'
end
